//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerElement
    {
        public int Element_ID { get; set; }
        public string Header_Text { get; set; }
        public string Image_Path { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Content_ID { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public Nullable<System.DateTime> Date_Archive { get; set; }
        public string Archive_By { get; set; }
        public bool Archived { get; set; }
        public int Banner_ID { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Updated_By { get; set; }
        public string Added_By { get; set; }
        public Nullable<int> Content_Type_ID { get; set; }
    
        public virtual Banner Banner { get; set; }
        public virtual ContentType ContentType { get; set; }
    }
}
