//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calender
    {
        public Calender()
        {
            this.PageCalenderAssigns = new HashSet<PageCalenderAssign>();
            this.Events = new HashSet<Event>();
        }
    
        public int Calender_ID { get; set; }
        public string Calender_Name { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Date_Archived { get; set; }
        public string Archived_By { get; set; }
        public bool Archived { get; set; }
    
        public virtual ICollection<PageCalenderAssign> PageCalenderAssigns { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
