//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.PageCollectionAssigns = new HashSet<PageCollectionAssign>();
            this.Posts = new HashSet<Post>();
        }
    
        public int Collection_ID { get; set; }
        public string Collection_Title { get; set; }
        public string Collection_Description { get; set; }
        public Nullable<int> Width_Mode_ID { get; set; }
        public int Display_Mode_ID { get; set; }
        public bool Archived { get; set; }
    
        public virtual CollectionsDisplayMode CollectionsDisplayMode { get; set; }
        public virtual CollectionsWidthMode CollectionsWidthMode { get; set; }
        public virtual WidthMode WidthMode { get; set; }
        public virtual ICollection<PageCollectionAssign> PageCollectionAssigns { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
