//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONNEXDBEntities : DbContext
    {
        public CONNEXDBEntities()
            : base("name=CONNEXDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Banner> Banners { get; set; }
        public DbSet<Calender> Calenders { get; set; }
        public DbSet<CollectionsDisplayMode> CollectionsDisplayModes { get; set; }
        public DbSet<CollectionsWidthMode> CollectionsWidthModes { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<ContentType> ContentTypes { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<Library> Libraries { get; set; }
        public DbSet<MediaType> MediaTypes { get; set; }
        public DbSet<PageAdminAssign> PageAdminAssigns { get; set; }
        public DbSet<PageCalenderAssign> PageCalenderAssigns { get; set; }
        public DbSet<PageCollectionAssign> PageCollectionAssigns { get; set; }
        public DbSet<PageGalleryAssign> PageGalleryAssigns { get; set; }
        public DbSet<PageLibraryAssign> PageLibraryAssigns { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<PageVideoGalleryAssign> PageVideoGalleryAssigns { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<VideoGallery> VideoGalleries { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<WidthMode> WidthModes { get; set; }
        public DbSet<Collection> Collections { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<BannerElement> BannerElements { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<PageQuickLinkListsAssign> PageQuickLinkListsAssigns { get; set; }
        public DbSet<QuickLinkList> QuickLinkLists { get; set; }
        public DbSet<QuickLink> QuickLinks { get; set; }
        public DbSet<NotificationRecipent> NotificationRecipents { get; set; }
        public DbSet<PageRecipientAssign> PageRecipientAssigns { get; set; }
    }
}
