//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        public ContentType()
        {
            this.BannerElements = new HashSet<BannerElement>();
        }
    
        public int Content_Type_ID { get; set; }
        public string Content_Type { get; set; }
        public string Display_Text { get; set; }
    
        public virtual ICollection<BannerElement> BannerElements { get; set; }
    }
}
