//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Document_Type_ID { get; set; }
        public string Content_Type { get; set; }
        public string Extension { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
    }
}
