//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Document_ID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<int> Library_ID { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Date_Archive { get; set; }
        public string Archive_By { get; set; }
        public bool Archived { get; set; }
        public int Document_Type_ID { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Library Library { get; set; }
    }
}
