//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Event_ID { get; set; }
        public string Event_Name { get; set; }
        public string Description { get; set; }
        public string Thumb_Path { get; set; }
        public string Image_Path { get; set; }
        public int Calender_ID { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Date_Archive { get; set; }
        public string Archive_By { get; set; }
        public bool Archived { get; set; }
        public System.DateTime Start_Date_Time { get; set; }
        public System.DateTime End_Date_Time { get; set; }
        public string Location { get; set; }
    
        public virtual Calender Calender { get; set; }
    }
}
