//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.PageGalleryAssigns = new HashSet<PageGalleryAssign>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int Gallery_ID { get; set; }
        public string Gallery_Name { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Date_Archive { get; set; }
        public string Archive_By { get; set; }
        public bool Archived { get; set; }
    
        public virtual ICollection<PageGalleryAssign> PageGalleryAssigns { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
