//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public Library()
        {
            this.Documents = new HashSet<Document>();
            this.PageLibraryAssigns = new HashSet<PageLibraryAssign>();
        }
    
        public int Library_ID { get; set; }
        public string Library_Name { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Date_Archive { get; set; }
        public string Archive_By { get; set; }
        public bool Archived { get; set; }
        public string Title_Text { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PageLibraryAssign> PageLibraryAssigns { get; set; }
    }
}
