//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaType
    {
        public MediaType()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int Media_Type_ID { get; set; }
        public string Media_Types { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
