//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRecipent
    {
        public NotificationRecipent()
        {
            this.PageRecipientAssigns = new HashSet<PageRecipientAssign>();
        }
    
        public int Recipient_ID { get; set; }
        public string Recipient_Name { get; set; }
        public string Recipient_Email { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string Added_By { get; set; }
    
        public virtual ICollection<PageRecipientAssign> PageRecipientAssigns { get; set; }
    }
}
