//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickLinkList
    {
        public QuickLinkList()
        {
            this.PageQuickLinkListsAssigns = new HashSet<PageQuickLinkListsAssign>();
            this.QuickLinks = new HashSet<QuickLink>();
        }
    
        public int Link_List_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Archived { get; set; }
        public string Archived_By { get; set; }
        public bool Archived { get; set; }
    
        public virtual ICollection<PageQuickLinkListsAssign> PageQuickLinkListsAssigns { get; set; }
        public virtual ICollection<QuickLink> QuickLinks { get; set; }
    }
}
