//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Admins = new HashSet<Admin>();
        }
    
        public int Role_ID { get; set; }
        public string Role1 { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
    }
}
