//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int Section_ID { get; set; }
        public string Sub_Header { get; set; }
        public string Text_Block { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public string Media_Path { get; set; }
        public Nullable<int> Media_Width_Mode_ID { get; set; }
        public string Hyperlink { get; set; }
        public Nullable<int> Media_Type_ID { get; set; }
        public string Hyperlink_Text { get; set; }
    
        public virtual MediaType MediaType { get; set; }
        public virtual Post Post { get; set; }
        public virtual WidthMode WidthMode { get; set; }
    }
}
